name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Repo Lockdown'
        uses: dessant/repo-lockdown@v4
        with:
          pr-comment: >
            This repository does not accept pull requests.